# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

networks:
  ssl-reverse-proxy:
    external: true

services:
  distrowatch-gentoo-ev-org:
    build: .
    ports:
      - 127.0.0.1:50480:80
    networks:
      - default
      - ssl-reverse-proxy
    volumes:
      - ./htdocs/:/var/www/html:ro
    restart: unless-stopped

  distrowatch-cron:
    image: gentoo/stage3
    entrypoint: ["/root/entrypoint.bash"]
    command: []
    volumes:
      - ./entrypoint.bash:/root/entrypoint.bash
      - ./gentoo_x86_latest:/root/gentoo_x86_latest
      - ./htdocs/:/var/www/distrowatch-gentoo-ev-org/htdocs/
      - gentoo-repo:/var/db/repos/gentoo/
    restart: unless-stopped

volumes:
  gentoo-repo:
