# Copyright (C) 2023 Sebastian Pipping <sebastian@pipping.org>
# SPDX-License-Identifier: MIT

name: Build

# Drop permissions to minimum for security
permissions:
  contents: read

on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * 5'  # Every Friday at 2am
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Install dependencies
        run: |-
          sudo apt-get update
          sudo apt-get install --yes --no-install-recommends -V \
              docker-compose \
              wait-for-it

      - name: Build Docker image
        run: |-
          docker-compose build

      - name: Smoke-test Docker image
        run: |-
          set -x

          docker network create --internal ssl-reverse-proxy
          docker-compose up -d distrowatch-gentoo-ev-org

          docker-compose run -e LOOP=false distrowatch-cron
          ls -l htdocs/x86/

          wait-for-it 127.0.0.1:50480
          wget -O- http://127.0.0.1:50480/x86/latest_stable.txt \
              | grep -qF media-gfx/gimp
          wget -O- http://127.0.0.1:50480/x86/latest_unstable.txt \
              | grep -qF media-gfx/gimp

          docker-compose down
          docker network rm ssl-reverse-proxy
